# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-03 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('Αλμυρές', 'Αλμυρές'), ('Γλυκές', 'Γλυκές')], default='Αλμυρές', max_length=9),
        ),
    ]
