# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-03 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_material_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crepe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('descritpion', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('category', models.CharField(choices=[('Αλμυρές', 'Αλμυρές'), ('Γλυκές', 'Γλυκές')], default='Αλμυρές', max_length=9)),
            ],
        ),
    ]
