# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-12 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_crepe'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='mat_category',
            field=models.CharField(choices=[('Κρεατικά', 'Κρεατικά'), ('Τυριά', 'Τυριά'), ('Λαχανικα', 'Λαχανικα'), ('Διάφορα', 'Διάφορα')], default='Κρεατικά', max_length=9),
        ),
    ]
